# Generated by Django 4.2.7 on 2025-04-10 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrafikHeatmapCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("data", models.TextField()),
                ("point_count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TrafikSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("segment_id", models.CharField(max_length=100, unique=True)),
                (
                    "street_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("speed_limit", models.FloatField(default=0)),
                ("distance", models.FloatField(default=0)),
                ("latitude", models.FloatField(default=0)),
                ("longitude", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="TrafikTahmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("time_of_day", models.TimeField()),
                ("day_of_week", models.CharField(max_length=20)),
                ("distance", models.FloatField()),
                ("predicted_speed", models.FloatField()),
                ("predicted_time", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrafikVeri",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField()),
                ("harmonic_avg_speed", models.FloatField(default=0)),
                ("median_speed", models.FloatField(default=0)),
                ("average_speed", models.FloatField(default=0)),
                ("travel_time", models.FloatField(default=0)),
                ("sample_size", models.IntegerField(default=0)),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trafik_verileri",
                        to="trafik_app.trafiksegment",
                    ),
                ),
            ],
        ),
    ]
